"""add repository test runs

Revision ID: 77632c858823
Revises: ab134545ba7c
Create Date: 2026-07-28 17:16:46.986939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77632c858823'
down_revision: Union[str, Sequence[str], None] = 'ab134545ba7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('docker_image', sa.String(length=255), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('tests_ran', sa.Boolean(), nullable=False),
    sa.Column('has_local_changes', sa.Boolean(), nullable=False),
    sa.Column('has_remote_changes', sa.Boolean(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_test_runs_id'), 'repository_test_runs', ['id'], unique=False)
    op.create_index(op.f('ix_repository_test_runs_repository_id'), 'repository_test_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repository_test_runs_triggered_by_user_id'), 'repository_test_runs', ['triggered_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_test_runs_triggered_by_user_id'), table_name='repository_test_runs')
    op.drop_index(op.f('ix_repository_test_runs_repository_id'), table_name='repository_test_runs')
    op.drop_index(op.f('ix_repository_test_runs_id'), table_name='repository_test_runs')
    op.drop_table('repository_test_runs')
    # ### end Alembic commands ###
