"""add owner user to repositories

Revision ID: ab134545ba7c
Revises: 4ce0715ffad8
Create Date: 2026-07-27 18:08:53.095471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab134545ba7c'
down_revision: Union[str, Sequence[str], None] = '4ce0715ffad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('owner_user_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_index(op.f('ix_repositories_owner_user_id'), 'repositories', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'repositories', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_index(op.f('ix_repositories_owner_user_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=True)
    op.drop_column('repositories', 'owner_user_id')
    # ### end Alembic commands ###
